version: "0.1.0.{build}"
image: Visual Studio 2017

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))" }

install:
  - git submodule update --init --recursive
  - nuget restore

build_script:
  - ps: msbuild GGOMP.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU"

after_build:
  - ps: 7z a GGO.7z "$($env:APPVEYOR_BUILD_FOLDER)\bin\Release\*"
  - ps: Push-AppveyorArtifact GGO.7z

deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: "DkvKC8KRj8AipGu/oWW/J2e6jMWt2xXQfKU7oefFMsp0ZMfzz+OR9Y9XpML+ZmG4"
  artifact: /.*\.7z/
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
